/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.1-10-g18610b3+18610b31a2f6eb6b7d403cb41099aabf6b151e77

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM = {
    .x1000_deviceType = 0x12345678,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1012_COB_IDTimeStampObject = 0x00000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    .x1016_consumerHeartbeatTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0x03E8,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000000,
        .productCode = 0x00000000,
        .revisionNumber = 0x00000000,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1280_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x80000000,
        .COB_IDServerToClientRx = 0x80000000,
        .node_IDOfTheSDOServer = 0x01
    },
    .x1400_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000200,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1401_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000300,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1402_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000400,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1403_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000500,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1600_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x60110010,
        .applicationObject2 = 0x60120008,
        .applicationObject3 = 0x60130008,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1601_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x04,
        .applicationObject1 = 0x60210010,
        .applicationObject2 = 0x60220008,
        .applicationObject3 = 0x60230008,
        .applicationObject4 = 0x60270008,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1602_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x04,
        .applicationObject1 = 0x60300008,
        .applicationObject2 = 0x60310008,
        .applicationObject3 = 0x60320008,
        .applicationObject4 = 0x60370008,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1603_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x04,
        .applicationObject1 = 0x60400008,
        .applicationObject2 = 0x60410008,
        .applicationObject3 = 0x60420008,
        .applicationObject4 = 0x60470008,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000180,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x03E8,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x60010010,
        .applicationObject2 = 0x60680008,
        .applicationObject3 = 0x60580008,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    }
};

OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1001_errorRegister = 0x00,
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x6000_targetHeaterTemperature = 0x007D,
    .x6001_currentHeaterTemperature = 0x0000,
    .x6002_ADC_Temperature = 0x0000,
    .x6003_enableHeater = 0x00,
    .x6004_kp = 0x001E,
    .x6005_ki = 0x003C,
    .x6006_kd = 0x0008,
    .x6010_packageDispenserPulsesPerRevolution = 0x0C80,
    .x6011_packageDispenserRotatePulses = 0x0000,
    .x6012_packageDispenserRotateDirection = 0x00,
    .x6013_packageDispenserEnable = 0x00,
    .x6014_packageDispenserCurrentPulses = 0x0000,
    .x6018_packageDispenserState = 0x00,
    .x6019_packageDispenserControl = 0x00,
    .x6020_pillGatePulsesPerRevolution = 0x0C80,
    .x6021_pillGateRotatePulses = 0x0000,
    .x6022_pillGateRotateDirection = 0x00,
    .x6023_pillGateEnable = 0x00,
    .x6024_pillGateCurrentPulses = 0x0000,
    .x6027_pillGateMode = 0x00,
    .x6028_pillGateState = 0x00,
    .x6029_pillGateControl = 0x00,
    .x6030_rollerRotateSteps = 0x00,
    .x6031_rollerRotationSpeed = 0x64,
    .x6032_rollerRotateDirection = 0x00,
    .x6033_rollerCurrentSteps = 0x00,
    .x6034_rollerTargetBraker = 0x32,
    .x6035_rollerCurrentBraker = 0x00,
    .x6037_rollerMode = 0x00,
    .x6038_rollerState = 0x00,
    .x6039_rollerControl = 0x00,
    .x6040_packageLengthRotateSteps = 0x00,
    .x6041_packageLengthRotationSpeed = 0x64,
    .x6042_packageLengthRotateDirection = 0x00,
    .x6043_packageLengthCurrentSteps = 0x00,
    .x6044_packageLengthTargetBraker = 0x32,
    .x6045_packageLengthCurrentBraker = 0x00,
    .x6047_packageLengthMode = 0x00,
    .x6048_packageLengthState = 0x00,
    .x6049_packageLengthControl = 0x00,
    .x6050_valve1Control = 0x00,
    .x6051_valve2Control = 0x00,
    .x6052_valve3Control = 0x00,
    .x6053_valve4Control = 0x00,
    .x6054_valve1State = 0x00,
    .x6055_valve2State = 0x00,
    .x6056_valve3State = 0x00,
    .x6057_valve4State = 0x00,
    .x6058_valveState = 0x00,
    .x6060_reedSwitch1State = 0x00,
    .x6061_reedSwitch2State = 0x00,
    .x6062_reedSwitch3State = 0x00,
    .x6063_reedSwitch4State = 0x00,
    .x6064_reedSwitch5State = 0x00,
    .x6065_reedSwitch6State = 0x00,
    .x6066_reedSwitch7State = 0x00,
    .x6067_reedSwitch8State = 0x00,
    .x6068_reedSwitchState = 0x00,
    .x6070_squeezerSpeed = 0x01F4,
    .x6071_squeezerWaitTime = 0x05,
    .x6072_squeezerDirection = 0x00,
    .x6073_squeezerMode = 0x00,
    .x6078_squeezerState = 0x00,
    .x6079_squeezerControl = 0x00,
    .x6080_conveyorSpeed = 0x03E8,
    .x6081_conveyorStopByPhotoelectric = 0x00,
    .x6082_conveyorDirection = 0x00,
    .x6083_conveyorMode = 0x00,
    .x6088_conveyorState = 0x00,
    .x6089_conveyorControl = 0x00
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1401_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1402_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1403_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1600_RPDOMappingParameter[9];
    OD_obj_record_t o_1601_RPDOMappingParameter[9];
    OD_obj_record_t o_1602_RPDOMappingParameter[9];
    OD_obj_record_t o_1603_RPDOMappingParameter[9];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1A00_TPDOMappingParameter[9];
    OD_obj_var_t o_6000_targetHeaterTemperature;
    OD_obj_var_t o_6001_currentHeaterTemperature;
    OD_obj_var_t o_6002_ADC_Temperature;
    OD_obj_var_t o_6003_enableHeater;
    OD_obj_var_t o_6004_kp;
    OD_obj_var_t o_6005_ki;
    OD_obj_var_t o_6006_kd;
    OD_obj_var_t o_6010_packageDispenserPulsesPerRevolution;
    OD_obj_var_t o_6011_packageDispenserRotatePulses;
    OD_obj_var_t o_6012_packageDispenserRotateDirection;
    OD_obj_var_t o_6013_packageDispenserEnable;
    OD_obj_var_t o_6014_packageDispenserCurrentPulses;
    OD_obj_var_t o_6018_packageDispenserState;
    OD_obj_var_t o_6019_packageDispenserControl;
    OD_obj_var_t o_6020_pillGatePulsesPerRevolution;
    OD_obj_var_t o_6021_pillGateRotatePulses;
    OD_obj_var_t o_6022_pillGateRotateDirection;
    OD_obj_var_t o_6023_pillGateEnable;
    OD_obj_var_t o_6024_pillGateCurrentPulses;
    OD_obj_var_t o_6027_pillGateMode;
    OD_obj_var_t o_6028_pillGateState;
    OD_obj_var_t o_6029_pillGateControl;
    OD_obj_var_t o_6030_rollerRotateSteps;
    OD_obj_var_t o_6031_rollerRotationSpeed;
    OD_obj_var_t o_6032_rollerRotateDirection;
    OD_obj_var_t o_6033_rollerCurrentSteps;
    OD_obj_var_t o_6034_rollerTargetBraker;
    OD_obj_var_t o_6035_rollerCurrentBraker;
    OD_obj_var_t o_6037_rollerMode;
    OD_obj_var_t o_6038_rollerState;
    OD_obj_var_t o_6039_rollerControl;
    OD_obj_var_t o_6040_packageLengthRotateSteps;
    OD_obj_var_t o_6041_packageLengthRotationSpeed;
    OD_obj_var_t o_6042_packageLengthRotateDirection;
    OD_obj_var_t o_6043_packageLengthCurrentSteps;
    OD_obj_var_t o_6044_packageLengthTargetBraker;
    OD_obj_var_t o_6045_packageLengthCurrentBraker;
    OD_obj_var_t o_6047_packageLengthMode;
    OD_obj_var_t o_6048_packageLengthState;
    OD_obj_var_t o_6049_packageLengthControl;
    OD_obj_var_t o_6050_valve1Control;
    OD_obj_var_t o_6051_valve2Control;
    OD_obj_var_t o_6052_valve3Control;
    OD_obj_var_t o_6053_valve4Control;
    OD_obj_var_t o_6054_valve1State;
    OD_obj_var_t o_6055_valve2State;
    OD_obj_var_t o_6056_valve3State;
    OD_obj_var_t o_6057_valve4State;
    OD_obj_var_t o_6058_valveState;
    OD_obj_var_t o_6060_reedSwitch1State;
    OD_obj_var_t o_6061_reedSwitch2State;
    OD_obj_var_t o_6062_reedSwitch3State;
    OD_obj_var_t o_6063_reedSwitch4State;
    OD_obj_var_t o_6064_reedSwitch5State;
    OD_obj_var_t o_6065_reedSwitch6State;
    OD_obj_var_t o_6066_reedSwitch7State;
    OD_obj_var_t o_6067_reedSwitch8State;
    OD_obj_var_t o_6068_reedSwitchState;
    OD_obj_var_t o_6070_squeezerSpeed;
    OD_obj_var_t o_6071_squeezerWaitTime;
    OD_obj_var_t o_6072_squeezerDirection;
    OD_obj_var_t o_6073_squeezerMode;
    OD_obj_var_t o_6078_squeezerState;
    OD_obj_var_t o_6079_squeezerControl;
    OD_obj_var_t o_6080_conveyorSpeed;
    OD_obj_var_t o_6081_conveyorStopByPhotoelectric;
    OD_obj_var_t o_6082_conveyorDirection;
    OD_obj_var_t o_6083_conveyorMode;
    OD_obj_var_t o_6088_conveyorState;
    OD_obj_var_t o_6089_conveyorControl;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &OD_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1280_SDOClientParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1401_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1402_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1403_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_6000_targetHeaterTemperature = {
        .dataOrig = &OD_RAM.x6000_targetHeaterTemperature,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6001_currentHeaterTemperature = {
        .dataOrig = &OD_RAM.x6001_currentHeaterTemperature,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6002_ADC_Temperature = {
        .dataOrig = &OD_RAM.x6002_ADC_Temperature,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6003_enableHeater = {
        .dataOrig = &OD_RAM.x6003_enableHeater,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6004_kp = {
        .dataOrig = &OD_RAM.x6004_kp,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6005_ki = {
        .dataOrig = &OD_RAM.x6005_ki,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6006_kd = {
        .dataOrig = &OD_RAM.x6006_kd,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6010_packageDispenserPulsesPerRevolution = {
        .dataOrig = &OD_RAM.x6010_packageDispenserPulsesPerRevolution,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6011_packageDispenserRotatePulses = {
        .dataOrig = &OD_RAM.x6011_packageDispenserRotatePulses,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6012_packageDispenserRotateDirection = {
        .dataOrig = &OD_RAM.x6012_packageDispenserRotateDirection,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6013_packageDispenserEnable = {
        .dataOrig = &OD_RAM.x6013_packageDispenserEnable,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6014_packageDispenserCurrentPulses = {
        .dataOrig = &OD_RAM.x6014_packageDispenserCurrentPulses,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6018_packageDispenserState = {
        .dataOrig = &OD_RAM.x6018_packageDispenserState,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6019_packageDispenserControl = {
        .dataOrig = &OD_RAM.x6019_packageDispenserControl,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6020_pillGatePulsesPerRevolution = {
        .dataOrig = &OD_RAM.x6020_pillGatePulsesPerRevolution,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6021_pillGateRotatePulses = {
        .dataOrig = &OD_RAM.x6021_pillGateRotatePulses,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6022_pillGateRotateDirection = {
        .dataOrig = &OD_RAM.x6022_pillGateRotateDirection,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6023_pillGateEnable = {
        .dataOrig = &OD_RAM.x6023_pillGateEnable,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6024_pillGateCurrentPulses = {
        .dataOrig = &OD_RAM.x6024_pillGateCurrentPulses,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6027_pillGateMode = {
        .dataOrig = &OD_RAM.x6027_pillGateMode,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6028_pillGateState = {
        .dataOrig = &OD_RAM.x6028_pillGateState,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6029_pillGateControl = {
        .dataOrig = &OD_RAM.x6029_pillGateControl,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6030_rollerRotateSteps = {
        .dataOrig = &OD_RAM.x6030_rollerRotateSteps,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6031_rollerRotationSpeed = {
        .dataOrig = &OD_RAM.x6031_rollerRotationSpeed,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6032_rollerRotateDirection = {
        .dataOrig = &OD_RAM.x6032_rollerRotateDirection,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6033_rollerCurrentSteps = {
        .dataOrig = &OD_RAM.x6033_rollerCurrentSteps,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6034_rollerTargetBraker = {
        .dataOrig = &OD_RAM.x6034_rollerTargetBraker,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_6035_rollerCurrentBraker = {
        .dataOrig = &OD_RAM.x6035_rollerCurrentBraker,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_6037_rollerMode = {
        .dataOrig = &OD_RAM.x6037_rollerMode,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6038_rollerState = {
        .dataOrig = &OD_RAM.x6038_rollerState,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6039_rollerControl = {
        .dataOrig = &OD_RAM.x6039_rollerControl,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6040_packageLengthRotateSteps = {
        .dataOrig = &OD_RAM.x6040_packageLengthRotateSteps,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6041_packageLengthRotationSpeed = {
        .dataOrig = &OD_RAM.x6041_packageLengthRotationSpeed,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6042_packageLengthRotateDirection = {
        .dataOrig = &OD_RAM.x6042_packageLengthRotateDirection,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6043_packageLengthCurrentSteps = {
        .dataOrig = &OD_RAM.x6043_packageLengthCurrentSteps,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6044_packageLengthTargetBraker = {
        .dataOrig = &OD_RAM.x6044_packageLengthTargetBraker,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_6045_packageLengthCurrentBraker = {
        .dataOrig = &OD_RAM.x6045_packageLengthCurrentBraker,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_6047_packageLengthMode = {
        .dataOrig = &OD_RAM.x6047_packageLengthMode,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6048_packageLengthState = {
        .dataOrig = &OD_RAM.x6048_packageLengthState,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6049_packageLengthControl = {
        .dataOrig = &OD_RAM.x6049_packageLengthControl,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6050_valve1Control = {
        .dataOrig = &OD_RAM.x6050_valve1Control,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6051_valve2Control = {
        .dataOrig = &OD_RAM.x6051_valve2Control,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6052_valve3Control = {
        .dataOrig = &OD_RAM.x6052_valve3Control,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6053_valve4Control = {
        .dataOrig = &OD_RAM.x6053_valve4Control,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6054_valve1State = {
        .dataOrig = &OD_RAM.x6054_valve1State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6055_valve2State = {
        .dataOrig = &OD_RAM.x6055_valve2State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6056_valve3State = {
        .dataOrig = &OD_RAM.x6056_valve3State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6057_valve4State = {
        .dataOrig = &OD_RAM.x6057_valve4State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6058_valveState = {
        .dataOrig = &OD_RAM.x6058_valveState,
        .attribute = ODA_SDO_RW | ODA_TPDO,
        .dataLength = 1
    },
    .o_6060_reedSwitch1State = {
        .dataOrig = &OD_RAM.x6060_reedSwitch1State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6061_reedSwitch2State = {
        .dataOrig = &OD_RAM.x6061_reedSwitch2State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6062_reedSwitch3State = {
        .dataOrig = &OD_RAM.x6062_reedSwitch3State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6063_reedSwitch4State = {
        .dataOrig = &OD_RAM.x6063_reedSwitch4State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6064_reedSwitch5State = {
        .dataOrig = &OD_RAM.x6064_reedSwitch5State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6065_reedSwitch6State = {
        .dataOrig = &OD_RAM.x6065_reedSwitch6State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6066_reedSwitch7State = {
        .dataOrig = &OD_RAM.x6066_reedSwitch7State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6067_reedSwitch8State = {
        .dataOrig = &OD_RAM.x6067_reedSwitch8State,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6068_reedSwitchState = {
        .dataOrig = &OD_RAM.x6068_reedSwitchState,
        .attribute = ODA_SDO_RW | ODA_TPDO,
        .dataLength = 1
    },
    .o_6070_squeezerSpeed = {
        .dataOrig = &OD_RAM.x6070_squeezerSpeed,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6071_squeezerWaitTime = {
        .dataOrig = &OD_RAM.x6071_squeezerWaitTime,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6072_squeezerDirection = {
        .dataOrig = &OD_RAM.x6072_squeezerDirection,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6073_squeezerMode = {
        .dataOrig = &OD_RAM.x6073_squeezerMode,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6078_squeezerState = {
        .dataOrig = &OD_RAM.x6078_squeezerState,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6079_squeezerControl = {
        .dataOrig = &OD_RAM.x6079_squeezerControl,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6080_conveyorSpeed = {
        .dataOrig = &OD_RAM.x6080_conveyorSpeed,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6081_conveyorStopByPhotoelectric = {
        .dataOrig = &OD_RAM.x6081_conveyorStopByPhotoelectric,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6082_conveyorDirection = {
        .dataOrig = &OD_RAM.x6082_conveyorDirection,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6083_conveyorMode = {
        .dataOrig = &OD_RAM.x6083_conveyorMode,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6088_conveyorState = {
        .dataOrig = &OD_RAM.x6088_conveyorState,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6089_conveyorControl = {
        .dataOrig = &OD_RAM.x6089_conveyorControl,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1010, 0x05, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &ODObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &ODObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &ODObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &ODObjs.o_1280_SDOClientParameter, NULL},
    {0x1400, 0x04, ODT_REC, &ODObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1401, 0x04, ODT_REC, &ODObjs.o_1401_RPDOCommunicationParameter, NULL},
    {0x1402, 0x04, ODT_REC, &ODObjs.o_1402_RPDOCommunicationParameter, NULL},
    {0x1403, 0x04, ODT_REC, &ODObjs.o_1403_RPDOCommunicationParameter, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_RPDOMappingParameter, NULL},
    {0x1602, 0x09, ODT_REC, &ODObjs.o_1602_RPDOMappingParameter, NULL},
    {0x1603, 0x09, ODT_REC, &ODObjs.o_1603_RPDOMappingParameter, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x6000, 0x01, ODT_VAR, &ODObjs.o_6000_targetHeaterTemperature, NULL},
    {0x6001, 0x01, ODT_VAR, &ODObjs.o_6001_currentHeaterTemperature, NULL},
    {0x6002, 0x01, ODT_VAR, &ODObjs.o_6002_ADC_Temperature, NULL},
    {0x6003, 0x01, ODT_VAR, &ODObjs.o_6003_enableHeater, NULL},
    {0x6004, 0x01, ODT_VAR, &ODObjs.o_6004_kp, NULL},
    {0x6005, 0x01, ODT_VAR, &ODObjs.o_6005_ki, NULL},
    {0x6006, 0x01, ODT_VAR, &ODObjs.o_6006_kd, NULL},
    {0x6010, 0x01, ODT_VAR, &ODObjs.o_6010_packageDispenserPulsesPerRevolution, NULL},
    {0x6011, 0x01, ODT_VAR, &ODObjs.o_6011_packageDispenserRotatePulses, NULL},
    {0x6012, 0x01, ODT_VAR, &ODObjs.o_6012_packageDispenserRotateDirection, NULL},
    {0x6013, 0x01, ODT_VAR, &ODObjs.o_6013_packageDispenserEnable, NULL},
    {0x6014, 0x01, ODT_VAR, &ODObjs.o_6014_packageDispenserCurrentPulses, NULL},
    {0x6018, 0x01, ODT_VAR, &ODObjs.o_6018_packageDispenserState, NULL},
    {0x6019, 0x01, ODT_VAR, &ODObjs.o_6019_packageDispenserControl, NULL},
    {0x6020, 0x01, ODT_VAR, &ODObjs.o_6020_pillGatePulsesPerRevolution, NULL},
    {0x6021, 0x01, ODT_VAR, &ODObjs.o_6021_pillGateRotatePulses, NULL},
    {0x6022, 0x01, ODT_VAR, &ODObjs.o_6022_pillGateRotateDirection, NULL},
    {0x6023, 0x01, ODT_VAR, &ODObjs.o_6023_pillGateEnable, NULL},
    {0x6024, 0x01, ODT_VAR, &ODObjs.o_6024_pillGateCurrentPulses, NULL},
    {0x6027, 0x01, ODT_VAR, &ODObjs.o_6027_pillGateMode, NULL},
    {0x6028, 0x01, ODT_VAR, &ODObjs.o_6028_pillGateState, NULL},
    {0x6029, 0x01, ODT_VAR, &ODObjs.o_6029_pillGateControl, NULL},
    {0x6030, 0x01, ODT_VAR, &ODObjs.o_6030_rollerRotateSteps, NULL},
    {0x6031, 0x01, ODT_VAR, &ODObjs.o_6031_rollerRotationSpeed, NULL},
    {0x6032, 0x01, ODT_VAR, &ODObjs.o_6032_rollerRotateDirection, NULL},
    {0x6033, 0x01, ODT_VAR, &ODObjs.o_6033_rollerCurrentSteps, NULL},
    {0x6034, 0x01, ODT_VAR, &ODObjs.o_6034_rollerTargetBraker, NULL},
    {0x6035, 0x01, ODT_VAR, &ODObjs.o_6035_rollerCurrentBraker, NULL},
    {0x6037, 0x01, ODT_VAR, &ODObjs.o_6037_rollerMode, NULL},
    {0x6038, 0x01, ODT_VAR, &ODObjs.o_6038_rollerState, NULL},
    {0x6039, 0x01, ODT_VAR, &ODObjs.o_6039_rollerControl, NULL},
    {0x6040, 0x01, ODT_VAR, &ODObjs.o_6040_packageLengthRotateSteps, NULL},
    {0x6041, 0x01, ODT_VAR, &ODObjs.o_6041_packageLengthRotationSpeed, NULL},
    {0x6042, 0x01, ODT_VAR, &ODObjs.o_6042_packageLengthRotateDirection, NULL},
    {0x6043, 0x01, ODT_VAR, &ODObjs.o_6043_packageLengthCurrentSteps, NULL},
    {0x6044, 0x01, ODT_VAR, &ODObjs.o_6044_packageLengthTargetBraker, NULL},
    {0x6045, 0x01, ODT_VAR, &ODObjs.o_6045_packageLengthCurrentBraker, NULL},
    {0x6047, 0x01, ODT_VAR, &ODObjs.o_6047_packageLengthMode, NULL},
    {0x6048, 0x01, ODT_VAR, &ODObjs.o_6048_packageLengthState, NULL},
    {0x6049, 0x01, ODT_VAR, &ODObjs.o_6049_packageLengthControl, NULL},
    {0x6050, 0x01, ODT_VAR, &ODObjs.o_6050_valve1Control, NULL},
    {0x6051, 0x01, ODT_VAR, &ODObjs.o_6051_valve2Control, NULL},
    {0x6052, 0x01, ODT_VAR, &ODObjs.o_6052_valve3Control, NULL},
    {0x6053, 0x01, ODT_VAR, &ODObjs.o_6053_valve4Control, NULL},
    {0x6054, 0x01, ODT_VAR, &ODObjs.o_6054_valve1State, NULL},
    {0x6055, 0x01, ODT_VAR, &ODObjs.o_6055_valve2State, NULL},
    {0x6056, 0x01, ODT_VAR, &ODObjs.o_6056_valve3State, NULL},
    {0x6057, 0x01, ODT_VAR, &ODObjs.o_6057_valve4State, NULL},
    {0x6058, 0x01, ODT_VAR, &ODObjs.o_6058_valveState, NULL},
    {0x6060, 0x01, ODT_VAR, &ODObjs.o_6060_reedSwitch1State, NULL},
    {0x6061, 0x01, ODT_VAR, &ODObjs.o_6061_reedSwitch2State, NULL},
    {0x6062, 0x01, ODT_VAR, &ODObjs.o_6062_reedSwitch3State, NULL},
    {0x6063, 0x01, ODT_VAR, &ODObjs.o_6063_reedSwitch4State, NULL},
    {0x6064, 0x01, ODT_VAR, &ODObjs.o_6064_reedSwitch5State, NULL},
    {0x6065, 0x01, ODT_VAR, &ODObjs.o_6065_reedSwitch6State, NULL},
    {0x6066, 0x01, ODT_VAR, &ODObjs.o_6066_reedSwitch7State, NULL},
    {0x6067, 0x01, ODT_VAR, &ODObjs.o_6067_reedSwitch8State, NULL},
    {0x6068, 0x01, ODT_VAR, &ODObjs.o_6068_reedSwitchState, NULL},
    {0x6070, 0x01, ODT_VAR, &ODObjs.o_6070_squeezerSpeed, NULL},
    {0x6071, 0x01, ODT_VAR, &ODObjs.o_6071_squeezerWaitTime, NULL},
    {0x6072, 0x01, ODT_VAR, &ODObjs.o_6072_squeezerDirection, NULL},
    {0x6073, 0x01, ODT_VAR, &ODObjs.o_6073_squeezerMode, NULL},
    {0x6078, 0x01, ODT_VAR, &ODObjs.o_6078_squeezerState, NULL},
    {0x6079, 0x01, ODT_VAR, &ODObjs.o_6079_squeezerControl, NULL},
    {0x6080, 0x01, ODT_VAR, &ODObjs.o_6080_conveyorSpeed, NULL},
    {0x6081, 0x01, ODT_VAR, &ODObjs.o_6081_conveyorStopByPhotoelectric, NULL},
    {0x6082, 0x01, ODT_VAR, &ODObjs.o_6082_conveyorDirection, NULL},
    {0x6083, 0x01, ODT_VAR, &ODObjs.o_6083_conveyorMode, NULL},
    {0x6088, 0x01, ODT_VAR, &ODObjs.o_6088_conveyorState, NULL},
    {0x6089, 0x01, ODT_VAR, &ODObjs.o_6089_conveyorControl, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
